[project]
name = "odoo-addons-oca-rest-framework"
version = "17.0.20240606.0"
dependencies = [
    "odoo-addon-fastapi>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
